baseURL = "https://yulongbb.github.io/"
languageCode = "zh-CN"
title = "大数据创新中心"
theme = "ananke"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
